In [7]:
import pandas as pd
dataset = pd.read_csv("Dataset/Training.csv")
dataset.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [9]:
## train test split
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [10]:
X = dataset.drop("prognosis", axis=1)
y = dataset['prognosis']

In [11]:
le= LabelEncoder()  ## convert string into integer value becouse machine understand only number
le.fit(y)
Y=le.transform(y)

In [12]:
x_train,x_test,y_train,y_test=train_test_split(X,Y, test_size=0.3, random_state=20)  # split data into x and y form 70:30 ratio 70 training data and 30 test data
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

In [14]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

# create a dictionry to store models

models={    
    "SVC":SVC(kernel='linear'),
    "RandomForst": RandomForestClassifier(n_estimators=100,random_state=42),
    "GradientBoosting":GradientBoostingClassifier(n_estimators=100,random_state=42),
    "Kneighbors":  KNeighborsClassifier(n_neighbors=5),
    "MultinomialNB":  MultinomialNB()                                                                      
}
for model_name, model in models.items():
    # train model
    model.fit(x_train,y_train)
    # test model
    prediction=model.predict(x_test)

    # calculate the accuracy of model
    acc=accuracy_score(y_test, prediction)
    # calculate the confusion metrix of model
    cm= confusion_matrix(y_test, prediction)
    print(f"{model_name}  Accuracy : {acc}")
    print(f"{model_name}  Confusion : ")
    print(np.array2string(cm, separator=', '))
    # print(f"{model_name} :  {model}")

SVC  Accuracy : 1.0
SVC  Confusion : 
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]
RandomForst  Accuracy : 1.0
RandomForst  Confusion : 
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]
GradientBoosting  Accuracy : 1.0
GradientBoosting  Confusion : 
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]
Kneighbors  Accuracy : 1.0
Kneighbors  Confusion : 
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]


## we will use single model

In [19]:
svm=SVC(kernel="linear")
# train the model
svm.fit(x_train,y_train)

# test the model
prediction= svm.predict(x_test)
#  calculate the accuracy of model
acc=accuracy_score(y_test,prediction)
# calculate the confusion matrix
cm= confusion_matrix(y_test, prediction)
print(f"ACCURACY : {acc}")
print(f" CONFUSION METRIX: {cm}")

ACCURACY : 1.0
 CONFUSION METRIX: [[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]


In [31]:
# save the model
import pickle
pickle.dump(svm ,open("models/svm.pkl",'wb'))

In [35]:
 #load model
sv = pickle.load(open('models/svm.pkl','rb'))

In [73]:
# test 01
print("Predicted label: ",svm.predict(x_test.iloc[6].values.reshape(1,-1)))
print("Actual Label:", y_test[6])

Predicted label:  [34]
Actual Label: 34


C:\Users\admin1\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [75]:
# test 02
print("Predicted label: ",svm.predict(x_test.iloc[10].values.reshape(1,-1)))
print("Actual Label:", y_test[10])

Predicted label:  [20]
Actual Label: 20


C:\Users\admin1\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


Recommendation system and prediction
load database and use logic for recommendations